add my project
hackclub/winter pull request #108
Opened 2022-12-24 22:27 UTC by WilmervH

## Describe your project in 1-3 sentences

We are building two smart chessboards with online play and local play against an AI. The project will be done together with @fellu4485. 

## Hack Club Slack handle

Wilmy

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

2022-12-24 22:32 UTC, fellu4485 commented
I will also participate in this project. My Hack Club Slack handle is: fellu

2022-12-26 01:16 UTC, exu3 requested changes
This is super neat! Your plan seems clear and sounds like a feasible project. I left a couple comments on your budget but everything else looks great.

2022-12-26 01:16 UTC, exu3 commented on WilmervH.md
> +| 2x Raspberry pi              | Dependant on availability
In order for Hack Club to give you money to purchase these, you'll need to provide a link to where you might find them. https://rpilocator.com/ may be helpful if you can find your country.

2022-12-26 01:16 UTC, exu3 commented on WilmervH.md
> +| 2x SD-card                   | [Muistikauppa.fi](https://www.muistikauppa.fi/tuote/kingston-canvas-select-plus-64gb-microsdxc-muistikortti/)
Would you happen to have an SD card reader for these?

2022-12-26 02:04 UTC, WilmervH commented
Hi! I own a SD-card reader and have added it to the tools section. We will probably buy the Raspberry Pis from buyzero.de. They do not show shipping fees until checkout but I am sure the fees can not be higher than the remaining budget.

2022-12-26 23:17 UTC, exu3 commented
> Hi! I own a SD-card reader and have added it to the tools section. We will probably buy the Raspberry Pis from buyzero.de. They do not show shipping fees until checkout but I am sure the fees can not be higher than the remaining budget.

https://buyzero.de/en/products/raspberry-pi-4-model-b-8gb?variant=40326644498612 appears to be sold out. Do you think you could find one in stock and link it in your document?

Other than that, I think this project is good to move forward!

2022-12-26 23:17 UTC, exu3 approved these changes

2022-12-27 18:52 UTC, MelSmith104 reviewed
hey @WilmervH and @fellu4485 ! i love your project idea so much! i love playing chess and this seems like its a great blend of both programming and chess :) i can't wait to learn more about it! i'm dm'ing the two of you on slack right now so that we can chat about next steps!

2022-12-29 21:26 UTC, MelSmith104 approved these changes

2022-12-29 21:26 UTC, merged