Create RileyCz.md
hackclub/winter pull request #111
Opened 2022-12-25 03:20 UTC by RileyCz

## Describe your project in 1-3 sentences

I am building a barometric altimeter which can either display a pressure altitude for a given barometric setting or display the current barometric pressure. 

## Hack Club Slack handle

Riley Czar

## Checklist before submitting proposal:

- [✅] I am a current high school student (or younger).
- [✅] I have submitted an RSVP at <https://hackclub.com/winter>
- [✅] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✅] I have self-reviewed my project proposal.

2022-12-27 14:52 UTC, exu3 requested changes
Thanks for submitting a proposal @RileyCz!

The project idea looks great, but I think your budget might be missing a few things. I left some comments and would love to hear your thoughts. Once you're ready, feel free to request another review.

2022-12-27 14:52 UTC, exu3 commented on RileyCz.md
> +
```suggestion
```

Remove empty line

2022-12-27 14:52 UTC, exu3 commented on RileyCz.md
> +| Solder Lead Free | [https://www.digikey.ca/en/products/detail/american-hakko-products,-inc./611-1/6228764](https://www.digikey.ca/en/products/detail/american-hakko-products,-inc./611-1/6228764)  |
If this is your first time soldering, I might also recommend getting a solder iron stand as well as other useful supplies like a solder sucker, solder wick, flux, tip cleaner, etc. Sometimes you can find these tools in kits. "Soldering kit" as a search query on Amazon seems to have a number of results.

2022-12-27 14:52 UTC, exu3 commented on RileyCz.md
> +| Total           |                                       | $142.21 |
Do you need a breadboard & wires for prototyping? Do you need any passives (resistors, capacitors, diodes, etc) for your circuit?

2022-12-27 18:42 UTC, RileyCz commented
> Thanks for submitting a proposal @RileyCz!
> 
> The project idea looks great, but I think your budget might be missing a few things. I left some comments and would love to hear your thoughts. Once you're ready, feel free to request another review.

Thanks for the suggestions. I think a breadboard will be helpful for prototyping and I have updated it with some things I think I may need. If I missed anything please let me know.

2022-12-28 16:45 UTC, exu3 approved these changes
Looks great! The @hackclub/bank-ops team will follow up with next steps on receiving your grant through Hack Club Bank.

Excited to see what you ship!

2022-12-28 17:53 UTC, MelSmith104 reviewed
hey @RileyCz ! your project looks amazing! i love that you chose it because you want to be a pilot - that is so cool! im dm'ing you on slack right now so that we can chat about next steps for the grant!

2022-12-29 23:29 UTC, MelSmith104 approved these changes

2022-12-29 23:31 UTC, merged