Added ArduinArm!
hackclub/winter pull request #114
Opened 2022-12-25 07:09 UTC by Skumm00

## Describe your project in 1-3 sentences

I am building a Bluetooth-controlled Robot arm using Arduino.

## Hack Club Slack handle

## Checklist before submitting the proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

2022-12-25 07:14 UTC, Skumm00 commented
My Slack Handle is Skand Bajpai.

2022-12-25 20:29 UTC, exu3 requested changes
Hello @Skumm00, your project proposal is looking great so far. Could you please rename the file to follow the `githubusername.md` format and address the comments below?

2022-12-25 20:29 UTC, exu3 commented on skumm00-proj.md
> +My project is going to be a custom-controlled, Arduino-powered, robot arm.
Could you please elaborate a bit more here?

Some prompts you may wish to answer in this section:
What excites you about building this project? Have you built similar hardware projects before? Why do you want to build this project?

2022-12-25 20:29 UTC, exu3 commented on skumm00-proj.md
> +I will be using a pre-existing set of 3d models for the overall structure of the robot arm. For the first 3 axes, the waist, the shoulder, and the elbow,
Could you link the 3D models here?

2022-12-25 20:29 UTC, exu3 commented on skumm00-proj.md
> +| Arduino UNO | [Amazon](https://www.amazon.com/Arduino-A000066-ARDUINO-UNO-R3/dp/B008GRTSV6/ref=as_li_ss_tl?keywords=arduino+uno&qid=1580073330&sr=8-3&linkCode=sl1&tag=howto045-20&linkId=2de9a9cd18c
Do you have a USB B cable you can use? It looks like the Arduino linked does not come with one.

2022-12-25 20:29 UTC, exu3 commented on skumm00-proj.md
> +| 3D printer  | [Amazon](https://www.amazon.com/Voxelab-Structure-Certified-Removable-8-66x8-66x9-84in/dp/B09BNG5884/ref=sr_1_8?crid=51ZBDXLXFTJD&keywords=3d%2Bprinter&qid=1671945440&sprefix=3d%2Bpri
What kind of filament are you planning to use?

2022-12-25 20:29 UTC, exu3 commented on skumm00-proj.md
> +| Total  | 257.80 + $17.30 tax  | $275.10 |
You can only get up to $250 with the grant; you'll have to cover the rest on your own by adding money to your Hack Club Bank account. Would you be able to cover this?

2022-12-26 07:41 UTC, Skumm00 commented
@exu3 how does it look now?

2022-12-26 07:43 UTC, Skumm00 commented
I've just found out I do have a USB-B cable at home, which is why it isn't included in the budget.

2022-12-28 17:12 UTC, exu3 approved these changes
Nice work! The @hackclub/bank-ops team will follow up with next steps on receiving your grant through Hack Club Bank.

Looking forward to seeing what you ship!

2022-12-28 17:12 UTC, exu3 commented on skumm00.md
> +My project is going to be a custom-controlled, Arduino-powered, robot arm. I've used 3-d printers and worked with Arduino circuits at my middle school, so I believe
```suggestion
My project is going to be a custom-controlled, Arduino-powered, robot arm. I've used 3D printers and worked with Arduino circuits at my middle school, so I believe
```

2022-12-28 17:12 UTC, exu3 commented on skumm00.md
> +the usage of automated engineering (like 3-d printers and CNCs) for industrial development, which is a field I would like to consider in the future.
```suggestion
the usage of automated engineering (like 3D printers and CNCs) for industrial development, which is a field I would like to consider in the future. 
```

2022-12-28 17:56 UTC, MelSmith104 reviewed
hey @Skumm00 ! i can't wait to see your robot arm come to life - this looks like such a cool project! im dm'ing you on slack right now so that we can chat about next steps!

2023-01-03 20:56 UTC, MelSmith104 approved these changes

2023-01-03 20:56 UTC, merged