Create e-c-centric.md
hackclub/winter pull request #151
Opened 2022-12-29 16:42 UTC by e-c-centric

## Describe your project in 1-3 sentences

## Hack Club Slack handle

## Checklist before submitting proposal:

- [#] I am a current high school student (or younger).
- [#] I have submitted an RSVP at <https://hackclub.com/winter>
- [#] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [#] I have self-reviewed my project proposal.

2023-01-02 15:36 UTC, bellesea requested changes
hiii @e-c-centric thank you sm for sharing this project idea, it's super cool! i'm wondering, are you referencing any guides/existing projects for this build?

also, i saw that within your bundles you'd be purchasing an Arduino UNO and an Arduino Nano RP2040 Connect, which do you plan on using?

thanks :)

2023-01-03 12:46 UTC, e-c-centric commented
Hiii @bellesea , thanks for your feedback :)

I am not referencing any guide per se, but I am referencing a lot of projects on the Arduino Project Hub. Also, I have older friends in uni who have worked/are working on IoT projects. I've got a lot of information from them on how to proceed. 

I plan on using the Arduino Nano RP2040 Connect because of its processor and capabilities. I also own an ESP32 that I'll try this project with. I'll likely go with the Arduino Nano because it significantly reduces the hassle through its Arduino Cloud connectivity and the power of the Raspberry Pi processor. the Arduino Uno comes together with a bundle of other stuff I need, so I can't exactly remove it. In the course of building this project, I might find a use for it 😃, maybe for a control experiment

thankss

2023-01-04 00:13 UTC, bellesea commented
> Hiii @bellesea , thanks for your feedback :)
> 
> I am not referencing any guide per se, but I am referencing a lot of projects on the Arduino Project Hub. Also, I have older friends in uni who have worked/are working on IoT projects. I've got a lot of information from them on how to proceed.
> 
> I plan on using the Arduino Nano RP2040 Connect because of its processor and capabilities. I also own an ESP32 that I'll try this project with. I'll likely go with the Arduino Nano because it significantly reduces the hassle through its Arduino Cloud connectivity and the power of the Raspberry Pi processor. the Arduino Uno comes together with a bundle of other stuff I need, so I can't exactly remove it. In the course of building this project, I might find a use for it 😃, maybe for a control experiment
> 
> thankss

hey @e-c-centric ahh that makes sense :) Unfortunately, i don't think we can approve a budget to buy two arduinos when you only need one?

what do you think about getting the IOT bundle https://store.arduino.cc/products/iot-bundle?variant=42614286844055 then purchasing other specific sensors that you're looking for? 

thank you :)

2023-01-04 10:09 UTC, e-c-centric commented
@bellesea thanks. I'll rework my budget by close of day today.

2023-01-04 14:22 UTC, bellesea commented
> @bellesea thanks. I'll rework my budget by close of day today.

great, no rush :) thanks sm!

2023-01-13 01:38 UTC, bellesea commented
heyy just checking, do you have what you need to program the arduino? (eg. a usb port on your computer)

2023-01-14 15:15 UTC, cfanoulis commented
Hello Elikem ! It has been a while since we've heard from you - and we need to know if you're still interested in a winter grant. If you are - please reply to this PR (or this email) within the next 48 hours - else we will be closing this proposal. Thanks :)

2023-01-15 08:15 UTC, e-c-centric commented
Hiiii @cfanoulis @bellesea , really sorry for my absence. I was really ill over the week, and just getting better.

2023-01-15 08:16 UTC, e-c-centric commented
> heyy just checking, do you have what you need to program the arduino? (eg. a usb port on your computer)

yes, I do

2023-01-15 09:33 UTC, cfanoulis commented
hey @e-c-centric, no worries! just needed to know if you're still interested in making this :) belle will get back to you on monday, as they are off for the weekend

have a hacky, uh, recovery? lol

2023-01-15 19:19 UTC, bellesea commented
hey @e-c-centric oh no :( hope you feel better soon! when do you think you'd be able to update the budget based on previous comments?

2023-01-17 06:23 UTC, e-c-centric commented
> hey @e-c-centric oh no :( hope you feel better soon! when do you think you'd be able to update the budget based on previous comments?

I'll do that by end of day today. Thanks

2023-01-17 06:46 UTC, e-c-centric commented
done :)

2023-01-18 03:33 UTC, bellesea requested changes
hey @e-c-centric thanks sm for pushing the changes!

a few more questions:
- are you referencing any guides of sorts?
- why do you need the screwdriver set haha?

thank you sm!

2023-01-18 07:35 UTC, e-c-centric commented
> hey @e-c-centric thanks sm for pushing the changes!
> 
> a few more questions:
> 
> * are you referencing any guides of sorts?
> * why do you need the screwdriver set haha?
> 
> thank you sm!

Hiii @bellesea , on the screwdriver set, I was planning to build a housing for the different parts of my project (microcontroller and sensors) because a lot of the data will be collected outside, and unmonitored. I was going to use wood, plastic/plexiglass, maybe some metal and glass. My school's workshop gives me access to these materials, and welding and soldering stations. What we don't have however, are screwdrivers (because students keep taking them away 😂). I foresee I'll have to join stuff a fair bit to make the housing, and I don't want to use nails or any other permanent joint because I might need to take it apart to reach the components.

On a reference guide, I'm referencing several IOT projects on the Arduino hub, as well as projects students I know in uni have undertaken.

2023-01-19 19:21 UTC, bellesea approved these changes
@e-c-centric haha i know what you mean about the screwdrivers!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps :)

approving to move forward but can you please:
- add a total to your budget
- add your plan for casing under your plan?

thank you sm!

2023-01-19 19:21 UTC, bellesea commented on e-c-centric.md
> +# Project Name
```suggestion
# IOT Weather Monitoring and Prediction Station
```

2023-01-19 23:54 UTC, e-c-centric commented
hiii @bellesea thank you so much :) . I've made the changes requested. I'm not sure if I committed them right though.

>

2023-01-20 18:33 UTC, bellesea commented
@e-c-centric this looks good, thanks!

2023-01-21 00:52 UTC, MelSmith104 reviewed
hey @e-c-centric! this project sounds so useful! i rely on my inaccurate (at times) weather app but this seems like a much better method :) im dm'ing you right now on slack to chat about next steps!

2023-01-21 00:54 UTC, MelSmith104 commented
hey @e-c-centric could you please let me know your slack id :)

2023-01-21 08:47 UTC, e-c-centric commented
> hey @e-c-centric could you please let me know your slack id :)

hii @MelSmith104 it's U04H6MP70RK

2023-01-23 18:02 UTC, MelSmith104 commented
just dm'ed you!

2023-01-28 23:15 UTC, closed without merging

2023-01-28 23:27 UTC, MelSmith104 commented
closing as we can only move forward with projects made by teens that are still in high school. really appreciate the time you put into your proposal and hope you decide to build it down the road!