initial proposal
hackclub/winter pull request #154
Opened 2022-12-30 04:51 UTC by citricacid2

## Describe your project in 1-3 sentences

I'm going to build a smart backpack that's loaded with all sorts of cool tech features! It'll include dynamic RGB, tons of expansion, and lots of power.

## Hack Club Slack handle

ayush

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

2023-01-02 18:12 UTC, bellesea requested changes
@citricacid2 this is sooo awesome! i'm wondering, are you following any guide of sorts for this? i'm also wondering, what made you decide to choose this specific microcontroller?

also, just to confirm, do you already have all of the tools you listed?

and, does your budget include shipping and taxes?

thank you!

2023-01-02 18:33 UTC, citricacid2 commented on citricacid2.md
> +- The zippers will have conductive . The LEDs can be used to indicate this.
oops yeah, let me fix that

2023-01-02 18:41 UTC, citricacid2 commented
> this is sooo awesome! 

Thank you so much!

> i'm wondering, are you following any guide of sorts for this?

Not really, i've been looking at kickstarters for other "smart backpacks" and taking their features for inspiration!

> i'm also wondering, what made you decide to choose this specific microcontroller?

I noticed that it had an IMU and an incredibly small footprint. I didn't want to make any promises, but theoretically I could use the IMU to detect rapid breaking and activate rear LEDs as an automatic break light, which would be really useful while biking on city streets.

> does your budget include shipping and taxes?

oops, i forgot taxes. I think everything has free shipping however. I will make the changes soon, thank you!

------
Also, I just wanted to check, if I need to reallocate my budget later down the line, would I be free to do so? (if I clearly document what changes I made and why)

2023-01-02 18:50 UTC, bellesea commented
> > this is sooo awesome!
> 
> Thank you so much!
> 
> > i'm wondering, are you following any guide of sorts for this?
> 
> Not really, i've been looking at kickstarters for other "smart backpacks" and taking their features for inspiration!
> 
> > i'm also wondering, what made you decide to choose this specific microcontroller?
> 
> I noticed that it had an IMU and an incredibly small footprint. I didn't want to make any promises, but theoretically I could use the IMU to detect rapid breaking and activate rear LEDs as an automatic break light, which would be really useful while biking on city streets.
> 
> > does your budget include shipping and taxes?
> 
> oops, i forgot taxes. I think everything has free shipping however. I will make the changes soon, thank you!
> 
> Also, I just wanted to check, if I need to reallocate my budget later down the line, would I be free to do so? (if I clearly document what changes I made and why)

@citricacid2 sounds good! please request a review again when you're ready for us to take a look hehe :) and yes 100%, you'd just chat w/ the hcb person you'd be in contact with then reflect the changes within your file! thanks :)

2023-01-02 21:14 UTC, citricacid2 commented
Ok, just added tax and fixed the thread problem, what now?

2023-01-02 21:19 UTC, bellesea approved these changes
@citricacid2 this is super cool and can't wait to see you work on this!!

a fabulous member of @hackclub/bank-ops will be reaching out within the next few days with next steps :) thanks for your patience!

2023-01-03 19:05 UTC, MelSmith104 reviewed
ahhh @citricacid2 this project sounds so amazing!!! i love love love the idea of building a smart backpack! im dm'ing you on slack right now to chat through next steps!

2023-01-03 19:30 UTC, MelSmith104 approved these changes

2023-01-03 19:31 UTC, merged