Eye Safe Pocket Blogger
hackclub/winter pull request #188
Opened 2023-01-03 13:25 UTC by notadroid1007

## Describe your project in 1-3 sentences
A very cool idea to make a portable blogger, with multiple options, bluetooth, camera, mic, and a an 7 color E-Ink display to protect your eyes always :)

## Hack Club Slack handle
@NeeravGupta

## Checklist before submitting proposal:

- [ x ] I am a current high school student (or younger).
- [ x ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ x ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ x ] I have self-reviewed my project proposal.

2023-01-03 13:51 UTC, anddddrew commented
Hi @notadroid1007, this project looks great. Excited to see you build this

Let me get a 2nd pair of eyes on this and from there we can go forward :)

2023-01-04 06:48 UTC, BadPotato1007 commented
> Hi @notadroid1007, this project looks great. Excited to see you build this
> 
> Let me get a 2nd pair of eyes on this and from there we can go forward :)

Sure! Thank you for your support in this hardware fest!

2023-01-04 14:11 UTC, notadroid1007 commented
> Hi @notadroid1007, this project looks great. Excited to see you build this
> 
> Let me get a 2nd pair of eyes on this and from there we can go forward :)

Sure! waiting for the reply!

2023-01-06 00:52 UTC, cfanoulis reviewed
Hello Neerav! This sounds very useful! Just checking a couple of things before we hit the big green button:

- Are you positive (pun intended) that the battery can power the Pi? I didn't see any connectors in your budget
- Have you accounted for shipping&taxes?

thx!

2023-01-06 10:47 UTC, BadPotato1007 commented
> Hello Neerav! This sounds very useful! Just checking a couple of things before we hit the big green button:
> 
>     * Are you positive (pun intended) that the battery can power the Pi? I didn't see any connectors in your budget
> 
>     * Have you accounted for shipping&taxes?
> 
> 
> thx!

Yes, I am positive. Also I already have the connectors, and thebattry module can charge the battery, and use the adapter as the main power supply at the same time!

2023-01-11 16:52 UTC, bellesea commented
Hi @notadroid1007! Thanks for your proposal. It's been almost a week since cf's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Thank you :)

2023-01-14 14:53 UTC, bellesea commented
Hello! Unfortunately 2 days have passed, which means that I'll be closing this PR as stale. If you still wish to pursue a grant please let us know by replying to this PR before Jan 15th at 11:59pm ET.

2023-01-15 11:10 UTC, notadroid1007 commented
hey! I am so sorry! I was out of town, and could not reply! I would love to make this project, if you issue me the grant!

2023-01-15 11:13 UTC, cfanoulis commented
hellooo! thanks for replying - i'm reopening this, please answer the following before eod today thanks :)
> 
    Are you positive (pun intended) that the battery can power the Pi? I didn't see any connectors in your budget
    Have you accounted for shipping&taxes?

2023-01-15 11:14 UTC, notadroid1007 commented
yes, I am positive that the battery can power the pi, as Ihave done it before, and I have the connectors, so I did not mention that in the bill!

2023-01-15 12:43 UTC, cfanoulis commented
pls include those (& any sales tax) in your budget with a price of 0, thanks :) we need to keep an accurate bill of materials for each project

2023-01-15 15:31 UTC, notadroid1007 commented
> pls include those (& any sales tax) in your budget with a price of 0, thanks :) we need to keep an accurate bill of materials for each project

Done! please check it and let me know!

2023-01-15 16:11 UTC, cfanoulis requested changes
I swear - final thing

2023-01-15 16:11 UTC, cfanoulis commented on notadroid1007.md
>  ## £205.80 GBP is $246.57 USD
```suggestion
## £209.90 GBP is $256.73 USD (approx.)
```

heyyyy thanks for including tax! after conversion you seem to be slightly above the 250USD grant limit - would you be able to cover the rest? thanks :)

2023-01-17 21:46 UTC, cfanoulis commented
hey neerav? just noticed this is actually over 250$, sorry for that! can you please confirm you can pay the amount over 250$ for this project? thx <3

2023-01-18 19:49 UTC, cfanoulis commented
@notadroid1007 see above^

2023-01-19 14:45 UTC, notadroid1007 commented
> hey neerav? just noticed this is actually over 250$, sorry for that! can you please confirm you can pay the amount over 250$ for this project? thx <3

hey! yes I am ready to pay the remaining amount from my own pocket :)

2023-01-19 22:02 UTC, cfanoulis approved these changes
perfect, tysm for bearing with me :) i can't wait to see you shipping this - remember, we're building the entire 10 days, so I'd love to maybe see some text-to-speech function for making your own audiobooks, like those narrators on some websites.

2023-01-19 22:03 UTC, cfanoulis commented
@hackclub/bank-ops will be in touch shortly to get you setup on Hack Club Bank :)

2023-01-21 00:56 UTC, MelSmith104 reviewed
hey @notadroid1007 i love this idea! i really love how it ties into another interest of yours :) im dm'ing you on slack right now to chat about next steps!

2023-02-01 15:54 UTC, hackliv commented
Neerav has decided to move forward with this project: https://github.com/hackclub/winter/pull/164 instead!

2023-02-01 15:54 UTC, closed without merging