RealTime GPS Data logger project
hackclub/winter pull request #199
Opened 2023-01-04 13:28 UTC by Ghost-Ashu

## Describe your project in 1-3 sentences

i will be building a realtime GPS Data Logger by using Google Maps API and NodeMCU ESP8266. It will Display the geographic location of a user or device on a Google map

## Hack Club Slack handle

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

2023-01-06 01:26 UTC, cfanoulis commented
Hey, this sounds very nice! real quick, can you please include your slack username in the PR description? thaanks!

2023-01-06 18:14 UTC, Ghost-Ashu commented
> Hey, this sounds very nice! real quick, can you please include your slack username in the PR description? thaanks!

Thank You so much i have updated my Slack username. 😊

2023-01-06 18:18 UTC, Ghost-Ashu reviewed
reviwed

2023-01-08 09:55 UTC, Ghost-Ashu commented on Ghost-Ashu.md
> +#### Email: ashutoshkumarsingh951@gmail.com
Sorry! for including my email, i have removed it.

2023-01-08 09:57 UTC, Ghost-Ashu commented on Ghost-Ashu.md
> +## Plan
i Have worked with Network based Iot Devices in my past. Specially! the GPS modules, so with the Circuit, i would not face any issues while building this project.

2023-01-08 09:58 UTC, Ghost-Ashu commented on Ghost-Ashu.md
> +--> i already have my casing for my project. and Necessary other requirements. This is my Dream Project as this would my first GPS module Project that i have worked in years. i would be happy if u ag
Casing for my Project i Have added it :)

2023-01-08 09:59 UTC, Ghost-Ashu commented on Ghost-Ashu.md
> +| Total                                            |                                                                                 | $167.6 |
yes! all the Products i have mentioned here are including all the Necessary Taxes and Shipping Charges keeping in mind.

2023-01-08 10:33 UTC, cfanoulis requested changes
Thanks for that. I can't understand what you'll be displaying on your screen - will it be an image from google maps?

Also, how will the NodeMCU & arduino be connected? Esp. considering the arduino device doesn't have WiFi capabilities - are both even required?

2023-01-14 15:12 UTC, cfanoulis commented
Hello Ghost! It has been a while since my last message - and we need to know if you're still interested in a winter grant. If you are - please reply to this PR (or this email) within the next 48 hours - else we will be closing this proposal. Thanks :)

2023-01-15 06:20 UTC, Ghost-Ashu commented
> Thanks for that. I can't understand what you'll be displaying on your screen - will it be an image from google maps?
> 
> Also, how will the NodeMCU & arduino be connected? Esp. considering the arduino device doesn't have WiFi capabilities - are both even required?
let me Explain u again,  GPS module in my project is  to determine the device's current location. The GPS module receives signals from a network of satellites orbiting the earth, and uses this information to calculate the device's latitude, longitude, and altitude.
The NodeMCU can act as the main controller, while the Arduino can handle the GPS module. The NodeMCU can send commands to the Arduino to retrieve the GPS data, and the Arduino can send the data back to the NodeMCU to be processed and stored.
🙁 i guess u got. i have also included all these details in my PR.
still from many days i keep changing the details according to your Guidelines.

2023-01-15 06:23 UTC, Ghost-Ashu commented
> Hello Ghost! It has been a while since my last message - and we need to know if you're still interested in a winter grant. If you are - please reply to this PR (or this email) within the next 48 hours - else we will be closing this proposal. Thanks :)

Sorry! for not replying due to my college  exams. i will be Thankful if my proposal gets accepted😊

2023-01-15 12:42 UTC, cfanoulis commented
hey - sorry for making too many questions - i really need to understand how your project works before I give the a-ok hah.

How does Google Maps tie into this? Will you be displaying location information on your display? or would you have a seperate website where the location would be shown

2023-01-15 14:24 UTC, Ghost-Ashu commented
> 

The location would be Displayed on my TFT screen. Where ever i go. The GPS module provides only GPS coordinates, which would not be much accurate or presise.  so I would be using an GCP ( google cloud platform) maps API for providing more accurate results from those coordinates.

2023-01-15 16:13 UTC, cfanoulis approved these changes
Great! Thank you so much for bearing with me here :)

A banker will be in touch (after the weekend) to get you setup on Bank. Enjoy the grant (responsibly)!

2023-01-15 17:51 UTC, Ghost-Ashu commented
> Great! Thank you so much for bearing with me here :)
> 
> A banker will be in touch (after the weekend) to get you setup on Bank. Enjoy the grant (responsibly)!

Thank you so much ❤️

2023-01-17 22:13 UTC, MelSmith104 reviewed
hey @Ghost-Ashu! this project sounds super interesting :) im dm'ing you on slack to chat about next steps for the grant!

2023-01-31 17:59 UTC, MelSmith104 commented
closing pr due to unanswered questions on Slack

2023-01-31 17:59 UTC, closed without merging