Create Shrey-Mehra.md
hackclub/winter pull request #217
Opened 2023-01-06 17:48 UTC by Shrey-Mehra

## Describe your project in 1-3 sentences

I, along with @SHREEYA2007, am building the project which is aimed at saving lives caused due to delays in treatment.

## Hack Club Slack handle

@Shrey Mehra
@Shreeya Rani

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

2023-01-06 17:50 UTC, SHREEYA2007 commented
Hi, I am Shreeya!

2023-01-09 17:52 UTC, bellesea commented
> Hi, I am Shreeya!

hey @SHREEYA2007 can you please confirm that you're

[ ] I am a current high school student (or younger).
[ ] I have submitted an RSVP at https://hackclub.com/winter
[ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[ ] I have self-reviewed my project proposal.

2023-01-09 18:22 UTC, bellesea requested changes
hiiii @Shrey-Mehra and @SHREEYA2007 :) this is REALLLYYY COOOL!

i have a few questions:
- what "medical properties" are you referring to?
- could you please elaborate on what the user interface would look like and how you plan on linking your device to the interface?
- what are you 3d printing within this project? 
- could you please elaborate on the roles of the items within your budget (eg. 3d printer, pi, sensors, etc.) an how they'd help make your machine work?

please respond to these questions by committing additional details to your file :) ideally we'd be able to visualise you building this project!

thank you :)

2023-01-09 18:22 UTC, bellesea commented on Shrey-Mehra.md
> +name: "@Shrey-Mehra"
```suggestion
name: ["@Shrey-Mehra", "@SHREEYA2007"]
```

2023-01-09 18:31 UTC, SHREEYA2007 commented
Hi @bellesea , is there any particular procedure to confirm that 
[ ] I am a current high school student (or younger).
[ ] I have submitted an RSVP at https://hackclub.com/winter
[ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[ ] I have self-reviewed my project proposal?

2023-01-09 18:36 UTC, bellesea commented
> Hi @bellesea , is there any particular procedure to confirm that [ ] I am a current high school student (or younger). [ ] I have submitted an RSVP at https://hackclub.com/winter [ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack) [ ] I have self-reviewed my project proposal?

please just respond with the list above and adding an [x] within it to check it off :)

2023-01-09 18:45 UTC, SHREEYA2007 commented
> > Hi, I am Shreeya!
> 
> hey @SHREEYA2007 can you please confirm that you're
> 
> [x] I am a current high school student (or younger). [x] I have submitted an RSVP at https://hackclub.com/winter [x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack) [x] I have self-reviewed my project proposal.

2023-01-10 15:58 UTC, Shrey-Mehra reviewed
We have Done with all the changes.

please let us know if any changes required 

Regards
Shrey Mehra

2023-01-11 16:20 UTC, bellesea commented
hey @Shrey-Mehra i saw that you added a pi screen, could you please add under your plan how you will be using it? thank you sm :)

2023-01-11 16:22 UTC, Shrey-Mehra commented
Hey @bellesea actually i need display for displaying the data or we can say as a interface
Thank you

2023-01-11 16:25 UTC, bellesea commented
> Hey @bellesea actually i need display for displaying the data or we can say as a interface Thank you

great! please commit this detail to your plan :)

2023-01-11 16:27 UTC, Shrey-Mehra commented
Sure I'll update it asap
Thank you sm:)

2023-01-11 16:32 UTC, Shrey-Mehra commented
Hey @bellesea i update about screen in plan
Thank you:)

2023-01-12 16:12 UTC, hackliv approved these changes
This sounds so awesome! I'd love to hear more about it. 😃 I'm dming you both now on Slack to chat about next steps for the grant!

2023-01-17 14:46 UTC, merged