Ultimate PC Speakers
hackclub/winter pull request #23
Opened 2022-12-19 13:44 UTC by Meesmeesie

## Describe your project in 1-3 sentences

## Hack Club Slack handle

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (
Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

[meesmeesie.md](https://github.com/hackclub/winter/files/10259674/meesmeesie.md)

2022-12-20 19:29 UTC, bellesea requested changes
hey @Meesmeesie thanks for submitting a PR and sharing your project! could you please add back the exu3.md file you deleted?

also, to confirm, are you following this guide? https://diyperks.com/the-ultimate-pc-sound-system/ if so, can you please expand on it within your plan as to what you'll actually be doing?

and, do you have all the equipment you need to build this? like machinery to cut the wood and soldering tools?

could you please also factor in shipping and taxes? 

thank you so much!

2022-12-28 01:20 UTC, bellesea commented
> hey @Meesmeesie thanks for submitting a PR and sharing your project! could you please add back the exu3.md file you deleted?
> 
> also, to confirm, are you following this guide? https://diyperks.com/the-ultimate-pc-sound-system/ if so, can you please expand on it within your plan as to what you'll actually be doing?
> 
> and, do you have all the equipment you need to build this? like machinery to cut the wood and soldering tools?
> 
> could you please also factor in shipping and taxes?
> 
> thank you so much!

hiii @Meesmeesie hope you're doing awesome! checking in to ask: are you still interested in moving forward on this project?

2023-01-07 19:43 UTC, cfanoulis commented
Hi @Meesmeesie! Thanks for your proposal. It's been a week since Belle's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

2023-01-08 11:57 UTC, Meesmeesie commented
Hi, I was busy with school. But I'm still interested so I'm going to change
this now!

Op za 7 jan. 2023 om 20:43 schreef Charalampos Fanoulis <
***@***.***>:

> Hi @Meesmeesie <https://github.com/Meesmeesie>! Thanks for your proposal.
> It's been a week since Belle's message and we want to know if you're still
> interested in the grant. Please reply in the next 48 hours to this PR (or
> this email) if you're still interested, else we'll be closing this
> proposal. Hacky New Year!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/winter/pull/23#issuecomment-1374588482>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKULWS6FSEOMIKQN4W7P52TWRHBOFANCNFSM6AAAAAATDMDNKU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-08 12:05 UTC, Meesmeesie commented
i'm going to follow the guide on that website and the full build guide
video on youtube (https://youtu.be/408HxcN2gw4), and I (my dad :)) have all
the tools we need. My dad and I are going to make this together, because it
is hard to do it alone!
And i have a question, I live in the Netherlands, and really don't know the
shipping and taxes! Can you look that up for me? And if it becomes too
pricey, I can buy the wood myself!

> Message ID: ***@***.***>
>>
>

2023-01-08 18:27 UTC, bellesea commented
@Meesmeesie great! could you please add that you'll be referencing both links within your file then we should be good to move forward?

also, for shipping and taxes that's calculated on checkout of the individual items you listed in your budget so if you click on the link to purchase and move forward to checkout then insert your address you should be able to see the shipping and taxes. this just helps ensure we give you enough hehe :) if you need more help with this, don't worry about it and we can work with you on this later on.

thank you!

2023-01-08 18:56 UTC, Meesmeesie commented
I’m done!

2023-01-08 19:06 UTC, bellesea commented on meesmeesie.md
> +# Hack Club Bank Sign
```suggestion
# Ultimate PC Sound System
```

2023-01-08 19:25 UTC, bellesea commented
@Meesmeesie thanks for pushing that! i'm looking over the build guide and noticed that two transformers and speakers are needed but noticed you only had one of each in your budget? did you plan on only doing one and modifying the design? also, do you have the wires you need?

the person also got a 4 channel amp as well as a digital to analog converter (or an auxiliary port connected directly to amps), do you need these?

and, for building your audio filter do you have the capacitors etc.?

thank you!

2023-01-18 16:55 UTC, bellesea commented
hey @Meesmeesie following up on my last message, could you please respond to it within the next 48 hours if you're interested in proceeding? thank you sm :)

2023-01-20 16:27 UTC, bellesea commented
hey @Meesmeesie i'll be closing this PR for now as it's been two days since my message. Since the deadline has passed, please re-open this PR within 48 hours if you're interested in proceeding or we won't be able to review your PR anymore. thank you so much!

2023-01-20 16:27 UTC, closed without merging