Nova Synthetica by koningAbel.
hackclub/winter pull request #230
Opened 2023-01-07 14:45 UTC by KoningAbel

## Describe your project in 1-3 sentences

Simple Synth to fiddle around with when bored. 

## Hack Club Slack handle
Abel

## Checklist before submitting proposal:

- [👍  ] I am a current high school student (or younger).
- [👍   ] I have submitted an RSVP at <https://hackclub.com/winter>
- [👍   ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ 👍  ] I have self-reviewed my project proposal.

2023-01-09 20:31 UTC, bellesea requested changes
hii @KoningAbel woah this is cool!! i do not know how to build a synth and can't wait to learn through watching you build this :)

btw, i saw you had a connector, do you need batteries?

given that you're experimenting as you build, if you need to request more funding later on, please communicate this w/ the bank person you'd be in touch with!

a fabulous member of @hackclub/bank-ops will be reaching out with next steps!

2023-01-10 07:45 UTC, KoningAbel commented
> btw, i saw you had a connector, do you need batteries?

I already have some batterys. Thanks for checking and taking a look at it.



> hey @KoningAbel this is such a cool project! i love the idea of synth :) im dm'ing you on slack right now to chat about next steps!

Great, see you there.

2023-01-20 16:41 UTC, bellesea approved these changes

2023-02-01 20:54 UTC, MelSmith104 commented
closing since i've been unable to get in touch with them

2023-02-01 20:54 UTC, closed without merging