Add my project
hackclub/winter pull request #231
Opened 2023-01-07 17:35 UTC by ultratrikx

## Describe your project in 1-3 sentences
I am building a full size 5" FPV drone from scratch. It will have bluetooth connectivity to your phone and be able to record cinematic footage with a camera attached to it. 

## Hack Club Slack handle
rohanth1056

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

2023-01-09 20:45 UTC, bellesea requested changes
hiii @ultratrikx this is really cool!!

i'm wondering:
- have you confirmed/researched that a go pro would work instead of a Foxeer camera?
- could you please add the products you already own? eg. VTX, goggles, etc.

thank you!

2023-01-09 20:45 UTC, bellesea commented on ultratrikx.md
> +3. Attacth radio, VTX, camera to frame
```suggestion
3. Attach radio, VTX, camera to frame
```

2023-01-09 22:10 UTC, ultratrikx commented
> hiii @ultratrikx this is really cool!!
> 
> i'm wondering:
> 
> * have you confirmed/researched that a go pro would work instead of a Foxeer camera?
It is possible to use a GoPro as a feed for the FPV but it results in high latency and thus isn't the best for highspeed maneuvers. While an adequate FPV camera is only $20 (and another $12 for the VTX), it would go beyond the $250 budget given. Regarding this, I was wondering if it would be possible for us to put in some money ourselves to fulfill our build ideas. That way I can use a proper FPV camera instead of a high-latency GoPro.

> * could you please add the products you already own? eg. VTX, goggles, etc.
Will do!

2023-01-09 22:15 UTC, ultratrikx reviewed
Updated list of products I own.

2023-01-10 03:42 UTC, thinkingjet commented
not from hack club but yo how're u planning on adding the bluetooth support? Like what'll it be used for cus u already have a controller listed in ur products list

2023-01-10 15:18 UTC, ultratrikx commented
> not from hack club but yo how're u planning on adding the bluetooth support? Like what'll it be used for cus u already have a controller listed in ur products list

The flight stack has built in bluetooth support which can be used to send flight information such as altitude and speed to a connected device.

2023-01-10 20:51 UTC, bellesea commented
hiii @ultratrikx yes you can definitely add some money yourselves :) once you update the budget we should be good to go with moving forward!

2023-01-10 20:54 UTC, ultratrikx commented
Awesome, tysm! Will update the budget then.

2023-01-11 02:39 UTC, bellesea approved these changes
@ultratrikx ahh love this!! 

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

ps. approving this to move forward but for the items you already have could you pease make it $0 and it's ok for the total to be over $250, we'd just give you up to $250 :) thank you sm!

2023-01-11 12:52 UTC, daisybanks approved these changes
@ultratrikx wow this is going to be one big drone! I'm dming you now on Slack to talk about next steps in getting you you're grant! :)

2023-01-16 17:12 UTC, merged