StevenJohnson12
hackclub/winter pull request #290
Opened 2023-01-12 21:57 UTC by StevenJohnson12

## Describe your project in 1-3 sentences

## @Steven Johnson

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

2023-01-12 23:26 UTC, wardecs commented
Honestly, this seems like a really cool idea. I'm interested to hear more! Keep me updated when you are done, i'd really like to see how this one turns out.

2023-01-13 19:20 UTC, cfanoulis requested changes
Hello Steven! Thanks for your proposal! I've commented on some few things on your budget/bill of materials. Please address those before we can move ahead :)

2023-01-13 19:20 UTC, cfanoulis commented on StevenJohnson12
> +| Flipper Zero Device   | https://shop.flipperzero.one/ | $169.00 + $7.40 shipping cost  |
Hi, it's very cool you're trying to use a flipper zero :) any reason you chose that over a simple microcontroller with a distance breakout board?

2023-01-13 19:20 UTC, cfanoulis commented on StevenJohnson12
> +1. Buy all required items listed in the budget. I already own most of the items needed for this project (connectors, breadboards, many other arduino components.
please include all the items in your budget (with a price of 0$), as we want to keep an accurate bill of materials

2023-01-13 19:20 UTC, cfanoulis commented on StevenJohnson12
> +| Total           |                                       | $226.90 |
I see you have noted shipping seperately, is it included in your total?
Also, have you accounted for sales taxes?

2023-01-13 19:40 UTC, cfanoulis requested changes
new review, new questions :)

2023-01-13 19:40 UTC, cfanoulis commented on StevenJohnson12
> +| 2x Antenna Reciever/Transmitter   | ALREADY OWN | $0.00  |
can you please detail what kind of antenna you're using?

2023-01-13 19:40 UTC, cfanoulis commented on StevenJohnson12
> +| Distance Sensor   | ALREADY OWN | $0.00  |
also please include what kind of sensor :)

2023-01-13 19:40 UTC, cfanoulis commented on StevenJohnson12
> +| Saudering Equipment   | ALREADY OWN | $0.00  |
```suggestion
| Soldering Equipment   | ALREADY OWN | $0.00  |
```
also, I assume you already have solder/wick/etc? if so, can you include that as well?

2023-01-13 20:03 UTC, cfanoulis reviewed
thanks for your proposal :) we're almost done (i swear)

do you plan on making/buying a case to hold your project? don't see anything in your budget 🔍

2023-01-14 15:05 UTC, cfanoulis approved these changes
lovin' the story behind this project, ngl. let's get you a grant - someone from @hackclub/bank-ops will be in touch to get you setup on Hack bank :)

2023-01-15 14:12 UTC, MelSmith104 reviewed
hey @StevenJohnson12 :) just updating it here that we're already chatting on slack!

2023-01-18 15:57 UTC, MelSmith104 approved these changes

2023-01-18 17:36 UTC, merged