Create BogdanShemetov.md
hackclub/winter pull request #291
Opened 2023-01-12 22:02 UTC by BogdanShemetov

## Describe your project in 1-3 sentences

We will automate the process of titration. It is a device widely used in Chemistry for measuring concentration of acid or base.

## Hack Club Slack handle
Shemetov Bohdan

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

2023-01-14 16:41 UTC, bellesea commented
heyy @BogdanShemetov thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough (from a quick glance, i'd appreciate a little more details) for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits).

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

2023-01-17 14:44 UTC, bellesea requested changes
hey @BogdanShemetov woah this is such a cool idea!!

a few things:
- can your friend please also comment on this PR confirming they have done the 4 checklist items?
- are you referencing any sort of guides for this?
- under your plan, can you please expand a little on how this machine would work? eg. how would a "user" say interact with this machine? 
- i saw that you're purchasing wires, do you have what you need to cut it?
- does your budget include shipping and taxes?

thank you!

2023-01-17 14:44 UTC, bellesea commented on BogdanShemetov.md
> +# Project Name
```suggestion
# Automatic titration
```

2023-01-17 14:44 UTC, bellesea commented on BogdanShemetov.md
> +Automatic titration
```suggestion
```

2023-01-19 13:16 UTC, BogdanShemetov commented
> hey @BogdanShemetov woah this is such a cool idea!!
> 
> a few things:
>
> * can your friend please also comment on this PR confirming they have done the 4 checklist items?
> * are you referencing any sort of guides for this?
> The project is based on this guide: https://projecthub.arduino.cc/iterjunior/51d08a30-bbf6-4fb1-89a1-dba09ec5fd56
> * under your plan, can you please expand a little on how this machine would work? eg. how would a "user" say interact with this machine?
>  The interaction will be done through a keypad and a screen, that's all that is needed
> * i saw that you're purchasing wires, do you have what you need to cut it?
>  Yes, we do have scissors an all other tools
> * does your budget include shipping and taxes?
> Yes, taxes are included and (approximate) shipping is mentioned at the end

> thank you!

2023-01-19 16:36 UTC, Heipl commented
hey @bellesea I'm the second member of the team with @BogdanShemetov , my nickname in Slack is Heipl and I can confirm that:
- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

2023-01-19 19:48 UTC, bellesea commented
@BogdanShemetov thanks for your response! i'm curious how this machine works... so what data does it collect, how is the data processed, what decisions does it make, and how does it execute on said decisions (eg. does it automatically add the right amount of acid?)? 

also, what role does your keypad & screen play?

also, with the guide you linked i noticed that within your budget you don't have a pump, temp sensor, etc.?

thank you sm!

2023-01-19 20:24 UTC, BogdanShemetov commented
> @BogdanShemetov thanks for your response! i'm curious how this machine works... so what data does it collect, how is the data processed, what decisions does it make, and how does it execute on said decisions (eg. does it automatically add the right amount of acid?)?
> 
> also, what role does your keypad & screen play?
> 
> also, with the guide you linked i noticed that within your budget you don't have a pump, temp sensor, etc.?

So our titrator collects the volume of the used solution(from the burette) and pH of the second solution. Then it displays a graph of pH and calculates the point of equilibrium. It turns on after the user enters all data for calculation and stops after reaching the point of equilibrium.
thank you!

2023-01-19 20:53 UTC, bellesea approved these changes
@BogdanShemetov this is super cool! 

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

approving to move forward but can you please:
- update your plan with the details that you mentioned?
- just to check is your valve compatible with a burette or smth that you have? 

thank you!

2023-01-21 00:59 UTC, MelSmith104 reviewed
hey @BogdanShemetov! this sounds like a fascinating project idea. id love to hear more about why you chose this to build :) im dm'ing you on slack right now to chat about next steps!

2023-01-21 16:13 UTC, BogdanShemetov commented
> * update your plan with the details that you mentioned?
> * just to check is your valve compatible with a burette or smth that you have?

our plan didn't change)

2023-01-22 22:06 UTC, bellesea commented
> > * update your plan with the details that you mentioned?
> > * just to check is your valve compatible with a burette or smth that you have?
> 
> our plan didn't change)

@BogdanShemetov i meant this detail. our goal for making the project plans open sourced is also so they can be looked on and referenced in the future so the more details you can add the better :) thank you!

> So our titrator collects the volume of the used solution(from the burette) and pH of the second solution. Then it displays a graph of pH and calculates the point of equilibrium. It turns on after the user enters all data for calculation and stops after reaching the point of equilibrium.

2023-01-23 20:06 UTC, BogdanShemetov commented
> > > * update your plan with the details that you mentioned?
> > > * just to check is your valve compatible with a burette or smth that you have?
> > 
> > 
> > our plan didn't change)
> 
> @BogdanShemetov i meant this detail. our goal for making the project plans open sourced is also so they can be looked on and referenced in the future so the more details you can add the better :) thank you!
> 
> > So our titrator collects the volume of the used solution(from the burette) and pH of the second solution. Then it displays a graph of pH and calculates the point of equilibrium. It turns on after the user enters all data for calculation and stops after reaching the point of equilibrium.

We update our plan.
Thank you

2023-01-27 14:43 UTC, merged