PC build and application
hackclub/winter pull request #372
Opened 2023-01-15 18:02 UTC by SantoshiUser

## Describe your project in 1-3 sentences

I am building a Music player application by building a pc from scratch

## Hack Club Slack handle

slack handle: Santoshi Ram

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

2023-01-16 05:10 UTC, bellesea commented
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

2023-01-18 22:14 UTC, cfanoulis requested changes
Hello there, thanks for taking time to prepare a proposal! I hate to bear bad news, but I'm going ahead and denying this proposal

Winter Hardware Wonderland grants are internded to get students making something _new_ with hardware, while getting down to the nitty-gritty of electrical engineering. Unfortunately, as belle mentioned, we do not feel like assembling a PC from commercially-sourced parts falls under scope for this grant

But fear not! I'm able to offer you a one-time extension to submit a new proposal - if you have more ideas, draft a new proposal & open a new PR by **January 21st, 00:00ET** that's gonna mention this PR's ID (#372)

2023-01-18 22:14 UTC, closed without merging

2023-01-19 07:37 UTC, SantoshiUser commented
> Hello there, thanks for taking time to prepare a proposal! I hate to bear bad news, but I'm going ahead and denying this proposal
> 
> Winter Hardware Wonderland grants are internded to get students making something _new_ with hardware, while getting down to the nitty-gritty of electrical engineering. Unfortunately, as belle mentioned, we do not feel like assembling a PC from commercially-sourced parts falls under scope for this grant
> 
> But fear not! I'm able to offer you a one-time extension to submit a new proposal - if you have more ideas, draft a new proposal & open a new PR by **January 21st, 00:00ET** that's gonna mention this PR's ID (#372)

Thanks for giving one-time extension to submit a new proposal.
so Do i update this PR and add my new proposal in same PR

2023-01-19 20:05 UTC, bellesea commented
@SantoshiUser please open a new PR and just mention this PR's ID (#372)

2023-01-19 20:06 UTC, bellesea commented
let us know if you need any help with this :)) thanks! looking forward to your PR :)