Create Gspidey123.md
hackclub/winter pull request #383
Opened 2023-01-15 21:50 UTC by Gspidey123

## Describe your project in 1-3 sentences

## Hack Club Slack handle

## Checklist before submitting proposal:

- [y] I am a current high school student (or younger).
- [y] I have submitted an RSVP at <https://hackclub.com/winter>
- [y] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [y] I have self-reviewed my project proposal.

2023-01-16 16:42 UTC, bellesea commented
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: this sounds super cool! i'm wondering, are you referencing any sort of guides for this and does your budget include shipping and taxes?)_

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

2023-01-17 20:38 UTC, Gspidey123 commented
Hi Belle,

I have double checked and think the file is properly formatted. I also have edited the PR to add some images and more detail to make it easier to understand how my project works. I have included shipping in the costs. Most of these are from Amazon Prime, so has free delivery. And I have included the delivery for the Nitinol springs. All the money is in pounds converted to US dollars.

The main hand will be 3D printed using an online file. However, I want try and innovate the field by using a shape memory alloy, so for the rest of it, I am not following a guide and am very much experimenting in the unknown. However, my older brother has more experience with electronics and materials, and he will be helping me if it gets too technical for me. 

Thanks,
Gokul

2023-01-18 01:09 UTC, bellesea commented
@Gspidey123 thanks so much for the additional context! and, a heads up that we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

2023-01-19 12:47 UTC, exu3 requested changes
I love the photos you included. I left some comments below. It's looking good so far!

2023-01-19 12:47 UTC, exu3 commented on Gspidey123.md
> +# Project Name
Could you update this to say your project name instead of "project name"?

2023-01-19 12:47 UTC, exu3 commented on Gspidey123.md
> +![WhatsApp Image 2023-01-15 at 15 10 54](https://user-images.githubusercontent.com/122729898/213000244-588885e6-2c4d-42c0-8eb8-2a77f40758a7.jpeg)
Could you update the Alt text here to describe what we see in the image?

2023-01-19 12:47 UTC, exu3 commented on Gspidey123.md
> +What materials will you need for your project? Where will you get them? How much does it cost? Please include all materials, including components you already own. Make sure to factor in shipping cost
```suggestion
```

2023-01-19 12:47 UTC, exu3 commented on Gspidey123.md
> +![image](https://user-images.githubusercontent.com/122729898/212999254-8a3df9b5-cd98-42a0-994e-6cc87d7454af.png)
Could you update the alt text here to describe what a user sees in the image?

2023-01-19 12:49 UTC, exu3 approved these changes
Once the comments above are addressed, your project will be good to go! 

The @hackclub/bank-ops team will DM you on Slack with next steps for receiving the grant.

2023-01-19 20:04 UTC, Gspidey123 commented
Thank you so much! I have edited the file and addressed all the comments.

2023-01-19 20:36 UTC, MelSmith104 reviewed
hi @Gspidey123! this project sounds fascinating! i remember hearing about nitinol and also thought it was super cool! im dm'ing you right now to chat about next steps!

2023-01-21 15:46 UTC, Gspidey123 commented
I'm really sorry but I cant seem to find the dm that you sent me. Will it be on slack?

2023-01-23 16:35 UTC, MelSmith104 commented
just dm'ed you again! im so sorry! idk why my last one didn't send :(

2023-02-02 17:51 UTC, MelSmith104 approved these changes

2023-02-02 22:49 UTC, MelSmith104 approved these changes

2023-02-02 22:52 UTC, merged