Update PULL_REQUEST_TEMPLATE.md
hackclub/winter pull request #388
Opened 2023-01-16 01:30 UTC by belizairebr25

## Describe your project in 1-3 sentences

## Hack Club Slack handle

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

2023-01-16 16:51 UTC, bellesea commented
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: can you please format your document similar to the example in the [README](https://github.com/hackclub/winter#readme)? thank you!)_

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

2023-01-19 12:56 UTC, exu3 requested changes
Hey @belizairebr25! It looks like you edited the wrong file. Did you follow the instructions in the README and create your own file with your project idea? If you're unsure about anything, feel free to ask in #hardware-party on Slack—we're here to help!

2023-01-19 22:39 UTC, belizairebr25 commented
Dear Ella,
I believe I have resolved the issue(s), sorry for the confusion.
Thank You
Brician Belizaire

On Thu, Jan 19, 2023 at 7:56 AM Ella ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @belizairebr25 <https://github.com/belizairebr25>! It looks like you
> edited the wrong file. Did you follow the instructions in the README and
> create your own file with your project idea? If you're unsure about
> anything, feel free to ask in #hardware-party on Slack—we're here to help!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/winter/pull/388#pullrequestreview-1261731966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQ7NBDU7QLZWSNKIJTJ333WTE2YDANCNFSM6AAAAAAT4GAYUU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-20 03:25 UTC, exu3 requested changes
Neat idea, @belizairebr25. I have formatted your file using [Markdown](https://www.markdownguide.org/cheat-sheet/); I just copy/pasted what you had put originally, so please edit/correct if there is anything missing. 

Could you add some more details in your proposal (see comments below)? It's almost there!

2023-01-20 03:25 UTC, exu3 commented on belizairebr25.md
> +1. Design wiring schematics and paper drafts to guide when wiring and to find any potential issues with the idea, as well as to aid in knowing quantities of what is needed.
What software might you be using to design this?

2023-01-20 03:25 UTC, exu3 commented on belizairebr25.md
> +4. Assemble the display and print the glasses frame.
Will you be creating your own 3D model for the frame, or using an open source model? Could you clarify this in your project proposal?

2023-01-20 03:25 UTC, exu3 commented on belizairebr25.md
> +| Copper sheet roll for making keyboard contacts                                                                                                 | https://www.amazon.com/gp/aw/d/B0B21S6J5R/ref=ox_sc_
Do you have tools to cut the copper sheet?

2023-01-20 18:59 UTC, belizairebr25 commented
I believe I have resolved the specified issues.

2023-01-20 19:02 UTC, exu3 approved these changes
Great, thanks @belizairebr25! Can't wait to see you build this.

@hackclub/bank-ops will review and follow up with next steps via Slack. Happy hacking.

2023-01-21 01:21 UTC, MelSmith104 reviewed
hey @belizairebr25 this is super cool! i love this idea and it sounds like it'll be so much fun to build and test out! im dm'ing you on slack right now to chat about next steps!

2023-01-24 02:04 UTC, MelSmith104 approved these changes

2023-01-24 02:06 UTC, merged