Create Hidden-black.md
hackclub/winter pull request #44
Opened 2022-12-20 06:59 UTC by Hidden-black

## Describe your project in 1-3 sentences

I am building a remote control Toy car with the help of Arduino, I also plan to use these parts for small projects like motion sensors and integrate it into the car (like when the car gets near a wall it turns) .

## Hack Club Slack handle

## Checklist before submitting proposal:

- [+] I am a current high school student (or younger).
- [+] I have submitted an RSVP at <https://hackclub.com/winter>
- [+] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [+] I have self-reviewed my project proposal.

2022-12-21 19:51 UTC, bellesea requested changes
@Hidden-black thank you for sharing these ideas hehe, they all sound awesome :) could you please elaborate on how you'll be going about each of your individual projects? and maybe focusing on 1-2 (like you mentioned the toy car) that you'd like to work on for the duration of the event?

please let me know if you have any questions :)) also, could you please factor in taxes/shipping? thank you!!

2022-12-23 14:42 UTC, Hidden-black commented
am i suppose to type it in the markdown file? Also under which section? And how much explanation is needed

2022-12-23 15:30 UTC, bellesea commented
@Hidden-black in response to your question, yes please add it in the markdown file under the ##plan section :) and 3-5 sentences each (or as much as you need) would be perfect!

2022-12-23 15:57 UTC, bellesea requested changes

2022-12-23 15:57 UTC, bellesea commented on Hidden-black.md
> +- Build the frame
@Hidden-black thanks for pushing the changes! how do you plan on building the frame?

also, is there a guide that you plan on referencing?

2022-12-23 16:30 UTC, bellesea approved these changes
@Hidden-black this is going to be super awesome!!! can't wait to see you work on this :) 

an awesome member of @hackclub/bank-ops will be reaching out with next steps!

2022-12-26 19:32 UTC, MelSmith104 reviewed
hi @Hidden-black ! i love that you're building a toy car! this project sounds like so much fun :) im dm'ing you on slack right now so that we can chat about next steps!

2023-01-13 01:45 UTC, bellesea commented
heyy just checking, do you have a usb port on your computer that you can use to program the arduino?

2023-01-15 18:46 UTC, bellesea commented
hey @Hidden-black :) you've been unresponsive w/ our team for a while so we're closing this PR, if you're interested in moving forward please reach out to your bank point of contact (or respond in this thread) within 48 hours. thank you!

2023-01-15 18:46 UTC, closed without merging