Project Update
hackclub/winter pull request #447
Opened 2023-01-30 05:53 UTC by samanthahuaa

_Project proposals are no longer being accepted as of January 15th, 2023 23:59 EST._

If this is a bug fix, documentation update, or other, please describe the purpose of this pull request below:

Hello! Right as we were placing an order for our parts, we realized we had duplicates of an item in our budget which resulted in a larger budget than we needed. With the extra money we had, we added some more tools that would be helpful. If these tools are not permitted, we will take them out. Thank you!

2023-01-30 20:42 UTC, cfanoulis requested changes
Good catch! Does the new prices include shipping & taxes?

2023-01-31 02:18 UTC, samanthahuaa commented
@cfanoulis Yes! Our prices include taxes and shipping. 

But as I was reviewing our budget once more, I realized we didn't get enough switch film for both of our keyboards 😭 So I have edited the file again. This new addition pushes us beyond the 500 dollars but we will be able to pay the difference and add the extra money needed into our HackClub Bank account.

2023-01-31 08:08 UTC, cfanoulis approved these changes
coolio thanks for that. handing off to @hackclub/bank-ops to disburse your grant!

2023-02-01 20:30 UTC, MelSmith104 approved these changes

2023-02-01 20:30 UTC, merged