dharun016 - Cyber Drone
hackclub/winter pull request #57
Opened 2022-12-21 06:19 UTC by dharun016

## Describe your project in 1-3 sentences

 Nowadays Quadcopters are playing major roles in all fields . So, it is exciting to do some projects on it. I do so much research on that finally I came up with idea that connecting Raspberry Pi to the quadcopter to create scripts that will allow us to prevent attacks and gain access

## Hack Club Slack handle

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

2022-12-22 15:46 UTC, bellesea requested changes
oh wow @dharun016 this sounds awesome!! what do you mean by "defence wireless attacks and take over control"? what type of attacks are you talking about and what's the role of a drone in defending against it?

also, how do you plan on integrating the raspberry pi w/ the drone?

thank you so much!

2022-12-22 15:46 UTC, bellesea commented on dharun016.md
> +# Hack Club Bank Sign
```suggestion
```

2022-12-22 15:46 UTC, bellesea commented on dharun016.md
> +![Hack Club Bank logo illuminated from behind with coloured LEDs](https://cloud-hysdwonkf-hack-club-bot.vercel.app/0img_2814.jpg)
```suggestion
```

2022-12-22 17:37 UTC, dharun016 commented
In malls, railways, and other public places some hackers provide free wifi's connections. Some people don't know about this so they use wifi as normal users. But connecting **hackers** will gain full to their devices and use it for personal gain then they stole their data and blackmail them for money So, there are so many peoples affected by it. 

So, I have a plan of connecting with Raspberry Pi which is Linux based OS it is easy to write scripts, I use tools like **Nmap, aircrack-ng, and others tools** to combine all of them to first scan all the wifi connections with Nmap (**hackers mostly run their connection on port 80 for gain access**) then collect that connection and analyze it with aircrack-ng to drop down the connection and take control their access with twin evil attack finally we fill the complaint with the with data(**IP, location  etc**)we have,

2022-12-22 17:55 UTC, bellesea commented
> 

oh wow! that sounds cool! so your plan is to fly the drone w/ the pi to scan these areas?

2022-12-22 17:59 UTC, dharun016 commented
Yep, scanning phishing wifi connection a

2022-12-22 18:11 UTC, bellesea commented
> Yep, scanning phishing wifi connection a

great! one super small thing, could you please recommit the exu3.md file? after that, we should be good to move onto next steps!!

2022-12-22 18:30 UTC, dharun016 commented on exu3.md
> ----
recommit

2022-12-22 18:35 UTC, dharun016 commented
Done

2022-12-22 18:44 UTC, bellesea approved these changes
wahoo!!! this is AWESOME @dharun016 :) an awesome member of @hackclub/bank-ops will be reaching out w/ next steps soon!

2022-12-22 20:03 UTC, hackliv commented
Hey @dharun016 this drone sounds cool! Looking at the file, I was a bit confused why "Hack Club Bank Sign" was the header and image. Is this a second project you're hoping to work on? Let me know you Slack handle too!

2022-12-22 20:17 UTC, bellesea commented
hey @dharun016 could you please update your PR w/ the information you shared in this comments w/ regards to your plan for your drone? 

please let us know if you need any help with this, thank you so much!

2022-12-22 20:18 UTC, bellesea requested changes
hey @dharun016 could you please update your PR w/ the information you shared in this comments w/ regards to your plan for your drone?

please let us know if you need any help with this, thank you so much!

2022-12-23 03:35 UTC, dharun016 commented
I add all comments to my readme file Thank you for help

2022-12-23 16:09 UTC, bellesea approved these changes
thank you so much!!

2022-12-24 13:08 UTC, dharun016 commented
Is there any procedures?

2022-12-26 19:42 UTC, bellesea commented
> Is there anyother procedures?

@dharun016 it looks good! thanks for following up :) we’re on a small crew right now due to the holidays but a cool peep from @hackclub/bank-ops will be following up with next steps!

2022-12-27 18:19 UTC, MelSmith104 reviewed
hi @dharun016 ! this project sounds very interesting and i'd love to learn more! @hackliv is currently out of office for the holidays so i'll be the one dm'ing you to chat about next steps!

2022-12-29 15:38 UTC, closed without merging

2022-12-29 15:38 UTC, dharun016 commented
I Don't Eligible For This Program