AI Voice Assistant
hackclub/winter pull request #59
Opened 2022-12-21 09:36 UTC by haitomns4173

## Describe your project in 1-3 sentences

I am making a voice assistant that will be used to answer queries as well as home automation.
I will use a Raspberry Pi board for this project.

## Hack Club Slack handle

Haitomns G

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

2022-12-22 19:25 UTC, bellesea requested changes
@haitomns4173 thanks so much for sharing your project!! what will you be learning through making this and how long do you think it'll take to do this?

2022-12-23 07:20 UTC, haitomns4173 commented
I wanted to explore the field of raspberry pi, I have never done projects in it so I was eager to learn about it more, and making that AI assistant will help me learn the basics and know much about it. 

About how long it will take, I will say about a week,

DAY 1: Learn about the components of Raspberry pi.
DAY 2: Set up Raspberry pi and take a tour of Raspberry Pi OS.
DAY 3: Installing the required scripts for Google and Amazon Assistants.
Day 4: Getting the API Keys and Tokens from Amazon and Google Developer's Accounts.
Day 5: Connecting the Raspberry Pi to Smart Home Devices and testing the connectivity.
Day 6: If everything works fine, make an enclosure to house Rasberry Pi in with the speaker.
Day 7: Backup Day if anything goes wrong.

Hope I answered all your question.

2022-12-23 13:03 UTC, bellesea commented
> I wanted to explore the field of raspberry pi, I have never done projects in it so I was eager to learn about it more, and making that AI assistant will help me learn the basics and know much about it.
> 
> About how long it will take, I will say about a week,
> 
> DAY 1: Learn about the components of Raspberry pi. DAY 2: Set up Raspberry pi and take a tour of Raspberry Pi OS. DAY 3: Installing the required scripts for Google and Amazon Assistants. Day 4: Getting the API Keys and Tokens from Amazon and Google Developer's Accounts. Day 5: Connecting the Raspberry Pi to Smart Home Devices and testing the connectivity. Day 6: If everything works fine, make an enclosure to house Rasberry Pi in with the speaker. Day 7: Backup Day if anything goes wrong.
> 
> Hope I answered all your questions.

hiiii @haitomns4173 thanks for such a comprehensive response :)) what do you think about adding something "unique" to your AI home voice assistant, like perhaps writing some of your own code or designing your own enclosure? something that makes it such that your project has a little bit more you in it?

2022-12-23 14:49 UTC, haitomns4173 commented
Yes I already own a desktop computer with all the required tools to setup the Pi so no problem there. I already own a SD Card reader to program the Pi with Raspberry Pi OS. 

Talking about adding things to the assistant, definitely I will make a really good in closure out of Wood or Card board to house all the things into it. It will tell now pretty good. 

Recently I have started to learn about speech synthesis and speech recognisation using python, I have already started building a small Assistant and adding feature to it, Surely gonna test it in the Raspberry Pi and who know someday I will be using my own Assistant to do all my works.

2022-12-23 15:31 UTC, bellesea commented
> Yes I already own a desktop computer with all the required tools to setup the Pi so no problem there. I already own a SD Card reader to program the Pi with Raspberry Pi OS.
> 
> Talking about adding things to the assistant, definitely I will make a really good in closure out of Wood or Card board to house all the things into it. It will tell now pretty good.
> 
> Recently I have started to learn about speech synthesis and speech recognisation using python, I have already started building a small Assistant and adding feature to it, Surely gonna test it in the Raspberry Pi and who know someday I will be using my own Assistant to do all my works.

@haitomns4173 thanks for the rapid response! could you please this additional context in the markdown file?

2022-12-23 17:08 UTC, haitomns4173 commented
Done making changes to the file. Have a look.

2022-12-23 19:36 UTC, bellesea commented on haitomns4173.md
> +Finally if everything is tested and working properly, u will amke a wooden I'd cardboard enclosure to put all the contents in it and make it a single unit.
```suggestion
Finally if everything is tested and working properly, I will make a wooden cardboard enclosure to put all the contents in it and make it a single unit.
```

2022-12-23 19:37 UTC, bellesea commented
@haitomns4173 could you please factor in shipping and taxes in your budget? thank you sm!

2022-12-24 02:10 UTC, haitomns4173 commented on haitomns4173.md
> +Finally if everything is tested and working properly, u will amke a wooden I'd cardboard enclosure to put all the contents in it and make it a single unit.
Thank you for correcting that!

2022-12-24 02:11 UTC, haitomns4173 commented
Hey, I have added the shipping and the tax cost.

2022-12-26 19:20 UTC, bellesea approved these changes
@haitomns4173 thank you for your patience with the review and for pushing the changes!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps! thank you :)

(btw, we're currently on a reduced skeleton team for the holidays so please give us some time)

2022-12-26 19:38 UTC, MelSmith104 reviewed
hey @haitomns4173 ! i love this project idea <3 it sounds like it'll be so much fun to build! i'm reaching out to you on slack right now so that we can chat about next steps!

2022-12-29 17:46 UTC, MelSmith104 approved these changes

2022-12-29 17:48 UTC, merged