Create KrauseOlly.md
hackclub/winter pull request #61
Opened 2022-12-21 13:16 UTC by KrauseOlly

## Describe your project in 1-3 sentences

## Hack Club Slack handle

## Checklist before submitting proposal:

- [Y ] I am a current high school student (or younger).
- [Y ] I have submitted an RSVP at <https://hackclub.com/winter>
- [Y ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [Y ] I have self-reviewed my project proposal.

2022-12-22 19:40 UTC, bellesea requested changes
hiii @KrauseOlly this is super cool! love that you're desiging your own camera housing! i'm wondering, how will your camera be sending information to your goggles?

also, you mentioned having various views but i see that you're purchasing only one camera? how many cameras do you plan on using?

thank you sm!

2022-12-22 19:40 UTC, bellesea commented on KrauseOlly.md
> +name: "@yourGitHubUsername"
```suggestion
name: "@KrauseOlly"
```

2022-12-23 02:19 UTC, KrauseOlly commented
> hiii @KrauseOlly this is super cool! love that you're desiging your own camera housing! i'm wondering, how will your camera be sending information to your goggles?
> 
> also, you mentioned having various views but i see that you're purchasing only one camera? how many cameras do you plan on using?
> 
> thank you sm!

Hello @bellesea to your first question the camera I am purchasing has a built in transmitter and I already have a receiver for the goggles at home. As for the various views for now I just plan on getting one camera working on the front panel of my go kart however later down the line when I have a bit more money I plan on adding a reverse and side cameras to the go kart. Hope this answers your question.

2022-12-23 02:52 UTC, bellesea commented
> > hiii @KrauseOlly this is super cool! love that you're desiging your own camera housing! i'm wondering, how will your camera be sending information to your goggles?
> > also, you mentioned having various views but i see that you're purchasing only one camera? how many cameras do you plan on using?
> > thank you sm!
> 
> Hello @bellesea to your first question the camera I am purchasing has a built in transmitter and I already have a receiver for the goggles at home. As for the various views for now I just plan on getting one camera working on the front panel of my go kart however later down the line when I have a bit more money I plan on adding a reverse and side cameras to the go kart. Hope this answers your question.

ahhh coool, thank you so much for clarifying!

2022-12-23 02:53 UTC, bellesea approved these changes
@KrauseOlly thanks so much for sharing this project idea!! it's sooo cool and good luck w/ the designing of the camera housing, hope you're able to build one that gets you the best footage :)

an awesome member of @hackclub/bank-ops will be reaching out w/ next steps soon (likely tmrw EST). thanks!

2022-12-23 20:22 UTC, MelSmith104 reviewed
hey @KrauseOlly omg this project looks amazing!!! im misread at first and thought you were building a go kart but this entire project sounds so cool and unique! i can't wait to see how you build it! dm'ing you on slack right now to talk about next steps :)

2022-12-27 22:18 UTC, MelSmith104 approved these changes

2022-12-27 22:18 UTC, merged