Create Erik-Dennis.md
hackclub/winter pull request #73
Opened 2022-12-22 08:26 UTC by Erik-Dennis

## Describe your project in 1-3 sentences

## Hack Club Slack handle

## Checklist before submitting proposal:

- [Y] I am a current high school student (or younger).
- [Y] I have submitted an RSVP at <https://hackclub.com/winter>
- [Y] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [Y] I have self-reviewed my project proposal.

2022-12-22 20:30 UTC, bellesea requested changes
hiii @Erik-Dennis this is super cool, thanks for submitting a PR! i'm wondering, what will you be learning from this process, how long do you think it'll take for you to set this up, and will you be writing any code?

thank you sm!

2022-12-22 21:23 UTC, Erik-Dennis commented
I'll be learning about device integration and networking. I wasn't planning on writing code for it, but I might extend the project and create a custom HTML webpage for the dashboard and look into using API's. The integration through home assistant would probably take 1-3 days depending on how much free time I have, the customization with the webpage would be an extension that would go over the 10 days and probably take a couple months on top school.

2022-12-22 23:35 UTC, bellesea commented on Erik-Dennis.md
> +Smart Device Controller
```suggestion
```

2022-12-22 23:35 UTC, bellesea commented on Erik-Dennis.md
> +
```suggestion
```

2022-12-22 23:35 UTC, bellesea commented on Erik-Dennis.md
> +# Project Name
```suggestion
# Smart Device Controller
```

2022-12-22 23:42 UTC, bellesea commented
> I'll be learning about device integration and networking. I wasn't planning on writing code for it, but I might extend the project and create a custom HTML webpage for the dashboard and look into using API's. The integration through home assistant would probably take 1-3 days depending on how much free time I have, the customization with the webpage would be an extension that would go over the 10 days and probably take a couple months on top school.

ahhh cool! thank you for the rapid response :) what we're looking for in project is something you spend a significant amount of time on, that you can add something to that makes it your own, and that you can learn from. do you think that this fits the criteria?

also, do you need to purchase an SD card and power supply compatible w/ the pi or do you already have that?

thank you sm!

2022-12-22 23:47 UTC, Erik-Dennis commented
I have a USB C charger I can add to it, it's not the official but it should work fine. I also have an SD card.

2022-12-22 23:50 UTC, Erik-Dennis commented
I think the end result meets that criteria. I haven't ever used home assistant but it'll be a learning process. The webpage is the end result I'm going for but like stated above that'll go over the 10 days.

2022-12-23 00:02 UTC, bellesea commented
> I think the end result meets that criteria. I haven't ever used home assistant but it'll be a learning process. The webpage is the end result I'm going for but like stated above that'll go over the 10 days.

sounds good, @Erik-Dennis could you please update your file with plans for the webpage? it's ok that it'll go over 10 days :) thank you sm!

2022-12-23 00:07 UTC, Erik-Dennis commented
Will do.

2022-12-23 03:14 UTC, bellesea commented
> Will do.

thanks for pushing the changes! btw, how do you plan on programming your pi 4? do you have a way to program the SD card or will you be connecting a monitor etc.?

2022-12-23 03:29 UTC, Erik-Dennis commented
Yeah I'll probably use Rufus or pi installer

2022-12-23 16:23 UTC, bellesea approved these changes
@Erik-Dennis can't wait to see you build this! maybe we could even control the lights in your room remotely hehe, that would be such a cool and fun zoom call!

a fabulous member of @hackclub/bank-ops will be reaching out with next steps :)

2022-12-23 20:52 UTC, MelSmith104 reviewed
hey @Erik-Dennis love your project idea! a smart controller would be so useful to have at the house! im dm'ing you on slack so that we can chat about getting you set up on Bank for the grant!

2022-12-30 21:29 UTC, MelSmith104 approved these changes

2022-12-30 21:30 UTC, merged